### ISSUE TITLE
Unable to deploy to Heroku

### ISSUE THREAD

**Issue by nishantc7** [nishantc7/iterapi-web#1]
I am unable to deploy this to heroku. 
As I runserver at heroku console it runs on IT's localhost.

**Comment by MartyMiniac** [comment]
https://www.codementor.io/@jamesezechukwu/how-to-deploy-django-app-on-heroku-dtsee04d4 It might help... Gonna try it.

**Comment by SubhrajitPrusty** [comment]
> 
> 
> https://www.codementor.io/@jamesezechukwu/how-to-deploy-django-app-on-heroku-dtsee04d4 It might help... Gonna try it.

this article is 3 years old dude
